fix clang headers to support HIP c kernels and to support OpenMP .  T…
ROCm-Developer-Tools/amd-llvm-project pull request #160
Opened 2020-09-15 20:00 UTC by gregrodgers

…his depricates the autoheader __clang_openmp_runtime_wrapper.h .  Both nvptx and amdgcn will use the autoheader opemp_wrappers/__clang_openmp_device-functions.h

With this PR we stop using libm device lib for OpenMP.

2020-09-15 22:12 UTC, JonChesterfield reviewed
Bigger change than anticipated, sadly. Thanks for writing this.

Rebasing on #158 (e.g. by applying that to amd-stg-openmp first) will remove some of the line noise and will let this apply directly to amd-stg-open, without manual intervention.

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Headers/__clang_hip_libdevice_declares.h
> +//__device__ __attribute__((const)) float __ocml_sqrt_rte_f32(float, float);
This looks like a breaking change - do we need to drop the second argument?

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Headers/__clang_hip_complex_builtins.h
> +#ifndef __CLANG_HIP_COMPLEX_BUILTINS
could be worth moving this out of extras as a second patch to make the line delta look less intimidating to review (on gerrit or on phab)

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Driver/ToolChains/Clang.cpp
> +       (getToolChain().getTriple().getArch() == llvm::Triple::amdgcn))) {
iirc there's an isAMDGCN() function available now which does that ^

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Headers/__clang_hip_libdevice_declares.h
> +#if defined(__cplusplus)
This looks sketchy. How about, somewhere near the top of the file, 
```
#if !defined(__cplusplus)
#include <stdbool.h>
#endif
```

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Headers/__clang_hip_libdevice_declares.h
> +#if defined(__cplusplus)
This compiles fine as C if the return uses return (__2f16){...}, don't need to disable it entirely. amd-stg-open already has that patch.

2020-09-15 22:12 UTC, JonChesterfield commented on clang/lib/Headers/__clang_hip_runtime_wrapper.h
> +#define _NULLPTR nullptr
This seems messy. We can return NULL in C++ and it'll do the right thing, or we can return 0 and that'll do the right thing too.

2020-09-25 18:07 UTC, ronlieb commented
seems to be not too invasive
interested to here if Sam is good with it all.

2020-09-25 19:48 UTC, aaronenyeshi requested changes
I'm fixing merge conflict if this was to merge into amd-stg-open and upstream master.

2020-09-25 19:48 UTC, aaronenyeshi commented on clang/lib/Driver/ToolChains/CommonArgs.cpp
> +//  Lets clean up this overloading!
These comments won't be needed when upstreaming.

2020-09-25 19:48 UTC, aaronenyeshi commented on clang/lib/Driver/ToolChains/CommonArgs.cpp
> +        SDL_Name != "hip_hcc" && SDL_Name != "m") {
`SDL_Name != "m"` is already used in line 1691. `if (SDL_Name != "omp" && SDL_Name != "cudart" && SDL_Name != "m"`

2020-09-25 19:48 UTC, aaronenyeshi commented on clang/lib/Headers/__clang_hip_math.h
> +double sinh(double x) { return __ocml_sinh_f64(x); }
where are the rest of the double functions? starting from acos to sincospi?

2020-09-25 19:48 UTC, aaronenyeshi commented on clang/lib/Headers/__clang_hip_math.h
> +float __saturatef(float x) { return (x < 0) ? 0 : ((x > 1) ? 1 : x); }
looks like the float intrinsics got cut short too. Missing __sincosf, __sinf, __cosf.

2020-09-25 19:48 UTC, aaronenyeshi commented on clang/lib/Headers/__clang_hip_runtime_wrapper.h
> +#define __private
is this define missing `_attribute__((address_space(5)))`

2020-09-25 20:52 UTC, yxsamliu commented on clang/lib/Headers/__clang_hip_math.h
> +__DEVICE__ inline uint64_t __make_mantissa_base8(const char *tagp) {
clang requires all headers uses prefix function parameter names with `__`

2020-09-25 21:48 UTC, aaronenyeshi requested changes

2020-09-25 21:48 UTC, aaronenyeshi commented on clang/lib/Headers/openmp_wrappers/complex
>  #endif
which ifdef/ifndef is this endif for?

2020-09-25 21:54 UTC, aaronenyeshi commented on clang/lib/Headers/openmp_wrappers/complex
>  #endif
this seems to end the header file.

2020-09-25 22:34 UTC, gregrodgers commented on clang/lib/Headers/__clang_hip_complex_builtins.h
> +#ifndef __CLANG_HIP_COMPLEX_BUILTINS
This is deleted.  Both amdgcn and nvptx use __clang_cuda_complex_builtins.h

2020-09-25 23:02 UTC, gregrodgers commented on clang/lib/Driver/ToolChains/CommonArgs.cpp
> +//  Lets clean up this overloading!
This was a reminder to me that we don't need three methods for AddStaticDeviceLibs.

2020-09-28 18:18 UTC, gregrodgers commented
I believe I have addressed all the comments.  I am ready to merge this for 11.9-1.  We should be able to delete libm from aomp-extras now.

2020-09-28 18:23 UTC, ronlieb commented
have you addressed the test failures ethan observed? and these that i observed ?
do you want us to retest with your latest patch 
They are all FORTRAN TESTS

Add to the list of tests breaking
Build errors:
Nekbone
SPEC ACCEL 550.pmd(peak; CE), 553.pclvrleaf(peak; CE), 556.psp(peak; CE), 563.pswim(peak; CE)
Spec hpc2021 619.clvleaf_s 635.weather_s/

2020-09-28 18:24 UTC, ronlieb requested changes
please address testing issues from ethan and i

2020-09-28 18:50 UTC, ronlieb commented
The following fortrran applocation fail because these symbols are unresolved with this patch applied to the build 

sqrt, exp, sin, cos, pow

2020-09-28 19:05 UTC, aaronenyeshi commented on clang/lib/Headers/openmp_wrappers/complex
> +#endif //__CLANG_OPENMP_COMPLEX__
If we end the header file here, the below code will not be used. Is that intended?

2020-09-28 20:05 UTC, estewart08 commented
Tested with gfx906:
**Smoke:**
math_modd of core dump memory access fault

**Hip-openmp:**
Quite a few failures in hip programs with openmp code, here is a snippet:
aomp_11.9-1/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:138:10: error: no matching function for call to '__ocml_isinf_4'
        (_ISINFd(__ac) || _ISINFd(__bd) || _ISINFd(__ad) || _ISINFd(__bc))) {
aomp_11.9-1/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:134:15: error: no matching function for call to '__ocml_copysign_f64'

**Apps:**
lulesh
error: call to 'pow' is ambiguous

snap
error: call to 'log2' is ambiguous

**Nekbone:**
lld: error: undefined symbol: sin
lld: error: undefined symbol: cos

2020-09-28 20:12 UTC, aaronenyeshi commented
> The following fortrran applocation fail because these symbols are unresolved with this patch applied to the build
> 
> sqrt, exp, sin, cos, pow

this is related to my comment on __clang_hip_math.h. They are missing several float and double functions. Somehow the list got chopped in half.
https://github.com/ROCm-Developer-Tools/amd-llvm-project/pull/160#discussion_r495196419
https://github.com/ROCm-Developer-Tools/amd-llvm-project/pull/160#discussion_r495196088

2020-09-28 20:12 UTC, gregrodgers commented
Sorry, we are not ready to merge.  The libm model provided a compiled library that made it easy for FORTRAN.  We cannot use header libraries with FORTRAN.

2020-10-01 19:19 UTC, gregrodgers commented
The latest commits add all the missing c functions.   And a method to build a linkable bitcode from the header files __clang_hip_math.h or __clang_cuda_math.h.  .  In the aomp-extras repo there is a PR to compile a simple c file that is used to create the link libraries starting with libm- and ending in .bc.   

One last change is needed so that the FORTRAN driver links to the libm bc libraries.

2020-10-04 04:29 UTC, estewart08 commented
Tested new patchset with gfx906:

**Nekbone:***
Pass

**Smoke:**
math_modff: core dump memory access fault

**Hip-openmp:**
Quite a few failures in hip programs with openmp code, here is a snippet:
aomp_11.9-1/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:138:10: error: no matching function for call to '__ocml_isinf_64'
(_ISINFd(__ac) || _ISINFd(__bd) || _ISINFd(__ad) || _ISINFd(__bc))) {
aomp_11.9-1/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:134:15: error: no matching function for call to '__ocml_copysign_f64'

**Apps:**
lulesh
error: call to 'pow' is ambiguous

snap
error: call to 'log2' is ambiguous

hpgmg-mp4
error: conflicting types for 'norm'
aomp_11.9-1/lib/clang/11.0.0/include/__clang_hip_math.h:351:1: note: previous implicit declaration is here norm(int __dim,

2020-10-06 16:57 UTC, gregrodgers commented
This PR is replaced by PR169
https://github.com/ROCm-Developer-Tools/amd-llvm-project/pull/169

2020-10-06 16:57 UTC, closed without merging