[DeviceRTL][AMDGPU] Split atmi_memcpy for d2h and h2d
ROCm-Developer-Tools/amd-llvm-project pull request #178
Opened 2020-10-16 15:30 UTC by pdhaliwal-amd

This patch is mostly NFC as the underlying copy is still done by generic atmi_memcpy. Call sites, however, are updated to use the respective copy method as they already know which direction they are going to copy in.  Future patch will remove the check for the direction from the memcpy implementation.

2020-10-16 15:37 UTC, ronlieb approved these changes

2020-10-16 15:45 UTC, JonChesterfield requested changes
Broadly reasonable, though more code than necessary.

If you look at the start of Runtime::Memcpy, which atmi_memcpy wraps, you'll find the current logic for guessing the direction of copy. We can use that to check the directions are consistent, but that may as well be a second patch.

2020-10-16 15:45 UTC, JonChesterfield commented on openmp/libomptarget/plugins/amdgpu/impl/atmi.cpp
> +atmi_status_t atmi_memcpy_h2d(hsa_signal_t sig, void *host_dest,
parameter names are backwards. h2d as in 'host to device' copies from host to device, so host_src and device_dst. Though src/dst seems fine too.

2020-10-16 15:45 UTC, JonChesterfield commented on openmp/libomptarget/plugins/amdgpu/impl/atmi_runtime.h
>  atmi_status_t atmi_memcpy(hsa_signal_t sig, void *dest, const void *src,
drop atmi_memcpy from header, helps catch call sites that have been missed from the patch

2020-10-16 15:45 UTC, JonChesterfield commented on openmp/libomptarget/plugins/amdgpu/src/rtl.cpp
> +                                          size_t size) {
The hsa_memory_copy hack should be in atmi_memcpy, as then it's in one place instead of four.

The two implementations are the same, other than the atmi_memcpy_ call, so can implement as one function that takes a pointer. Typing directly into this comment box so syntax may be slightly off:
```
template <typename F> // or use an explicitly typed function pointer
static atmi_status_t freesignalpool_memcpy_impl(void *dest, const void *src, size_t size, F func) {	

hsa_signal_t s = FreeSignalPool.pop();
if (s.handle == 0) {
  return ATMI_STATUS_ERROR;
}
atmi_status_t r = func(s, dest, src, size);
FreeSignalPool.push(s);
return r;
}

atmi_status_t freesignalpool_memcpy_h2d(void *dest, const void *src, size_t size) {	
  return freesignalpool_memcpy_impl(dest, src, size, atmi_memcpy_h2d);
}
atmi_status_t freesignalpool_memcpy_d2h(void *dest, const void *src, size_t size) {	
  return freesignalpool_memcpy_impl(dest, src, size, atmi_memcpy_d2h);
}
```

2020-10-19 06:36 UTC, pdhaliwal-amd commented
Updated with requested changes. I had seen atmi_memcpy_no_signal being used only in one place hostrpc_handler_SERVICE_DEMO method, so I had moved its definition for hostrpc_execute_service.

2020-10-19 11:03 UTC, JonChesterfield requested changes

2020-10-19 11:03 UTC, JonChesterfield commented on openmp/libomptarget/plugins/amdgpu/src/rtl.cpp
> +  using MemcpyFunc = std::function<atmi_status_t (hsa_signal_t,
Generally in favour of std::function, though it does induce some runtime overhead. As part of making this library exception proof (which is some way off), I'd prefer we go with the raw function pointer `using MemcpyFunc = atmi_status_t (*)(hsa_signal_t, void*,const void*, size_t)` or similar.

2020-10-19 12:33 UTC, JonChesterfield approved these changes

2020-10-19 12:34 UTC, JonChesterfield commented
LG, thanks. Please squash the three commits into one before committing.

2020-10-19 13:36 UTC, merged