Limit default number of teams to number of CUs
ROCm-Developer-Tools/amd-llvm-project pull request #204
Opened 2020-11-18 12:01 UTC by pdhaliwal-amd

Default number of teams when launched with #pragma omp target teams would be equal to the number of CUs. Previously it was hard coded to 128.

2020-11-18 12:07 UTC, ronlieb reviewed
have you compared performance before and afer this change with any of our openmpapps?
or other performance tests ?

2020-11-18 12:44 UTC, pdhaliwal-amd commented
Not yet. There is one aomp_mappings smoke which is failing right now. Most probably its checking the hard coded value of teams as 128. Since now that is changed, I think that test will need to be updated as well.

2020-11-18 13:22 UTC, ronlieb commented
regarding aomp_mappings test, its going to produce different output for number of teams as the range of gpus we see have varying number of CUs for different models.  i have seen numbers from 12 to 120. so we might want to add a num_teams caluse to make the test behave more uniformly

2020-11-18 14:34 UTC, JonChesterfield commented
`default number of teams is 1:1 with number of compute units` <- sounds reasonable to me

2020-11-25 13:18 UTC, gregrodgers requested changes
change the environment variable name to OMP_DEFAULT_TEAMS_PER_PROC   .  This same value can be used for other architectures and for host teams.   If this works out for us, we will want to put in a spec change request for OpenMP 5.2.

2020-11-25 14:14 UTC, gregrodgers commented
Per teams discussion, the name should be OMP_TARGET_TEAMS_PER_PROC.  Maybe in another pull request we can get an api called omp_get_device_num_procs(int devid) that would return the number of CUs or SMs on the device.

2020-11-25 14:33 UTC, gregrodgers approved these changes

2020-11-25 14:36 UTC, merged